### ISSUE TITLE
Publish plugin checksum included in dockerhub images

### ISSUE THREAD

**Issue by darioAnongba** [ConsenSys/quorum-hashicorp-vault-plugin#12]
Every compilation of the binary provides different outputs the value included in the github artifact (SHA256SUM) and the actual value for the plugin included in the built image does not match. 

The goal of this ticket is to make available a version of the SHA256SUM included in the dockerhub image so it can be used in the k8s operator.

**Comment by ggarri** [comment]
Is this really an issue? As far as I see it every compilation of a binary generates an unique output since some time based information, or randomized values in case of upx compressing process, might be included.
